language: python
dist: xenial
sudo: true

python:
  - 3.8.5
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libgranzottiPyTools --cov=libgranzottiPyTools
after_success:
  - codecov